# elasticsearch will server as the index search db
# kibana will server as the web ui of elasticsearch

elasticsearch:
    image: elasticsearch:7.1.1
    mem_limit: 1024m
    environment:
     - TZ=Asia/Shanghai
    ports:
     - "9200:9200"
    expose:
        - "9200"
        - "9300"

kibana:
    image: kibana:7.0.0
    ports:
     - "5601:5601"
    links:
     - elasticsearch